<template>
    <div style="background-color: #d1ecf1; padding: 0px 10px;" >

        <div class="container-fluid">
            <!-- with exactly one real trace loaded there is nothing to choose: auto-select it
                 (selectDefault) and reclaim the space. Autogenerated sequence-diagram clones are
                 excluded from the count, so visiting the Sequence tab never resurfaces this UI. -->
            <div v-if="realConnectionCount > 1" class="row justify-content-center">
                <p  style="margin-top: 10px;">Select a trace via the dropdown(s) below to visualize it in the stream graph</p>
            </div>
            <div v-if="realConnectionCount > 1" class="row justify-content-center">
                <ConnectionConfigurator v-if="config.connections.length > 0" :allGroups="store.groups" :connection="config.connections[0]" :canBeRemoved="false" :excludeAutoGenerated="true" :onConnectionSelected="onConnectionSelected" />
            </div>

            <div class="row justify-content-center">
                <div class="form-check form-check-inline me-3">
                    <input
                        id="waterfall-checkbox"
                        v-model="config.showwaterfall"
                        class="form-check-input"
                        type="checkbox"
                        name="waterfall-checkbox">
                    <label class="form-check-label" for="waterfall-checkbox">Show waterfall</label>
                </div>

                <div class="form-check form-check-inline">
                    <input
                        id="byteranges-checkbox"
                        v-model="config.showbyteranges"
                        class="form-check-input"
                        type="checkbox"
                        name="byteranges-checkbox">
                    <label class="form-check-label" for="byteranges-checkbox">Show byte ranges</label>
                </div>

                <button type="button" class="btn btn-primary ms-3" v-if="allowSelectAll" @click="selectAllConnections()" :disabled="config.connections.length === 0">Load all connections at once</button>
            </div>

            <div v-if="store.outstandingRequestCount === 0 && store.groups.length === 0" class="alert alert-danger" role="alert">Please load a trace file to visualize it</div>
            <div v-else-if="store.groups.length === 0" class="alert alert-warning" role="alert">Loading files...</div>

        </div>

    </div>
</template>

<style scoped>
    .row {
        padding-bottom: 10px;
    }

    .btn {
        margin: 0px 5px;
    }
</style>

<script lang="ts">
    import { defineComponent, markRaw, toRaw, type PropType } from "vue";
    import MultiplexingGraphConfig from "./data/MultiplexingGraphConfig";

    import ConnectionConfigurator from "@/components/shared/ConnectionConfigurator.vue";
    import { countRealConnections, getDefaultRealConnection } from "@/components/shared/helpers/ConnectionSelectionHelper";
    import { useConnectionStore } from "@/store/ConnectionStore";
    import Connection from "@/data/Connection";

    export default defineComponent({
        name: "MultiplexingGraphConfigurator",
        components: {
            ConnectionConfigurator,
        },
        props: {
            config: {
                type: Object as PropType<MultiplexingGraphConfig>,
                required: true,
            },
        },
        data() {
            return {
                store: useConnectionStore(),
            };
        },
        computed: {
            allowSelectAll(): boolean {
                // e.g., add ?multimultiplexing=true to the URL
                return  (window.location.toString().indexOf(":8080") >= 0) ||
                        (window.location.toString().indexOf("localhost") >= 0) ||
                        (window.location.toString().indexOf("multimultiplexing") >= 0); // only for local testing for now! // TODO: CLEAN UP
            },
            // only re-runs when the reactive group list changes (the groups' connection arrays
            // are markRaw'd) — a sequence-tab visit appending its simulated clone never flips this
            realConnectionCount(): number {
                return countRealConnections(this.store.groups);
            },
        },
        mounted() {
            if ( this.config.connections.length === 0 && this.store.groups.length > 0 ){
                this.selectDefault();
            }
        },
        updated() {
            if ( this.config.connections.length === 0 && this.store.groups.length > 0 ){
                this.selectDefault();
            }
        },
        methods: {
        onConnectionSelected(connection:Connection) {
            console.log("MultiplexingGraphConfigurator:onConnectionSelected : ", this.config, connection);

            this.config.connections = [ markRaw(toRaw(connection)) ];
        },

        selectAllConnections() {

            // TODO: just for paper results, remove!
            (window as any).holblockinfo = new Array<any>();

            let conns = [];
            for ( const group of this.store.groups ){
                //if ( group.filename.indexOf("DEMO") < 0 ){
                    conns.push( ...group.getConnections().map((connection) => markRaw(toRaw(connection))) );
                //}
            }

            // sort on filename. 
            // Otherwise, they're sorted in whatever order they were actually loaded from the filesystem, 
            // which seems wholly indeterministic.
            conns = conns.sort( (c1, c2) => (c1.parent.filename < c2.parent.filename) ? -1 : 1 );

            this.config.showwaterfall = true;
            this.config.showbyteranges = false;
            this.config.connections = conns;
        },

        selectDefault(){
            console.log("MultiplexingGraphConfigurator:selectDefault: adding new default connection configurator", this.store.groups);
            const defaultConnection = getDefaultRealConnection(this.store.groups);
            if ( defaultConnection !== undefined ){
                this.config.connections = [ markRaw(toRaw(defaultConnection)) ];
            }
        },
        },
    });

</script>
