<template>
    <div style="background-color: #d4edda; padding: 0px 10px;" >

        <div class="container-fluid">
            <!-- with exactly one real trace loaded there is nothing to choose: auto-select it
                 (selectDefault) and reclaim the space. Autogenerated sequence-diagram clones are
                 excluded from the count, so visiting the Sequence tab never resurfaces this UI. -->
            <div v-if="realConnectionCount > 1" class="row justify-content-center">
                <p  style="margin-top: 10px;">Select a trace via the dropdown(s) below to visualize it in the congestion graph</p>
            </div>
            <div v-if="realConnectionCount > 1" class="row justify-content-center">
                <ConnectionConfigurator v-if="config.connection !== undefined" :allGroups="store.groups" :connection="config.connection" :canBeRemoved="false" :excludeAutoGenerated="true" :onConnectionSelected="onConnectionSelected" />
            </div>
            <!-- NOT a .row: Bootstrap 5's anonymous-column selector (.row > *) forces every
                 direct child to width:100%, so bare buttons in a .row render full-width and
                 stacked (Bootstrap 4 didn't do this — silent migration regression). Plain
                 flexbox keeps the buttons inline and centered. -->
            <div class="d-flex justify-content-center flex-wrap button-row">
                <button type="button" class="btn btn-secondary" @click="resetZoom()">Reset zoom</button>
                <button type="button" class="btn btn-secondary" @click="useBrushX()" title="Click this button, then drag and drop a horizontal time range to zoom in on.">Zoom timerange</button>
                <button type="button" class="btn btn-secondary" @click="useBrush2d()" title="Click this button, then drag and drop a rectangular area to zoom in on.">Zoom area</button>
                <button type="button" class="btn btn-secondary" @click="useRuler()" title="Click this button or press R, then drag and drop a line to see the time and byte ranges it spans">Ruler (press R)</button>
                <button type="button" class="btn btn-secondary" @click="toggleCongestionGraph()">Toggle congestion info</button>
                <button type="button" class="btn btn-secondary" @click="toggleRTTZoom()">Toggle RTT zooming</button>
            </div>

            <div v-if="store.outstandingRequestCount === 0 && store.groups.length === 0" class="alert alert-danger" role="alert">Please load a trace file to visualize it</div>
            <div v-else-if="store.groups.length === 0" class="alert alert-warning" role="alert">Loading files...</div>

        </div>

    </div>
</template>

<style scoped>
    .row, .button-row {
        padding-bottom: 10px;
    }

    .btn {
        margin: 0px 5px;
    }
</style>

<script lang="ts">
    import { defineComponent, markRaw, toRaw, type PropType } from "vue";
    import CongestionGraphConfig from "./data/CongestionGraphConfig";
    import * as qlog from '@/data/QlogSchema';

    import ConnectionConfigurator from "@/components/shared/ConnectionConfigurator.vue";
    import { countRealConnections, getDefaultRealConnection } from "@/components/shared/helpers/ConnectionSelectionHelper";
    import { useConnectionStore } from "@/store/ConnectionStore";
    import Connection from "@/data/Connection";

    export default defineComponent({
        name: "CongestionGraphConfigurator",
        components: {
            ConnectionConfigurator,
        },
        props: {
            config: {
                type: Object as PropType<CongestionGraphConfig>,
                required: true,
            },
        },
        data() {
            return {
                store: useConnectionStore(),
            };
        },
        computed: {
            isClientSideTrace(): boolean {
                return  this.config.connection !== undefined &&
                        this.config.connection.vantagePoint !== undefined &&
                        (this.config.connection.vantagePoint.type === qlog.VantagePointType.client || this.config.connection.vantagePoint.flow === qlog.VantagePointType.client);
            },
            // only re-runs when the reactive group list changes (the groups' connection arrays
            // are markRaw'd) — a sequence-tab visit appending its simulated clone never flips this
            realConnectionCount(): number {
                return countRealConnections(this.store.groups);
            },
        },
        mounted() {
            if ( this.config.connection === undefined && this.store.groups.length > 0 ){
                this.selectDefault();
            }

            document.addEventListener('keyup', this.useRuler);
        },
        beforeUnmount() {
            document.removeEventListener("keyup", this.useRuler);
        },
        updated() {
            if ( this.config.connection === undefined && this.store.groups.length > 0 ){
                this.selectDefault();
            }
        },
        methods: {
        onConnectionSelected(connection:Connection) {
            console.log("CongestionGraphConfigurator:onConnectionSelected : ", this.config, connection);

            this.config.connection = markRaw(toRaw(connection));
        },

        resetZoom(){
            // TODO hook up properly
            this.config.renderer.resetZoom();
        },

        useBrushX(){
            // TODO hook up properly
            this.config.renderer.useBrushX();
        },

        useBrush2d(){
            // TODO hook up properly
            this.config.renderer.useBrush2d();
        },

        useRuler(evt:any = undefined) {
            if ( evt ){
                // console.error( " KEYUP ", evt );
                if ( evt.code !== "KeyR" ){
                    return;
                }
            }

            console.log("CongestionGraphConfigurator: Using ruler");

            this.config.renderer.useRuler();
        },

        toggleCongestionGraph(){
            // TODO hook up properly
            this.config.renderer.toggleCongestionGraph();
        },

        toggleRTTZoom() {
            this.config.renderer.toggleZoomingRTTGraph();
        },

        togglePerspective(){
            // TODO hook up properly
            this.config.renderer.togglePerspective();
        },

        selectDefault(){
            console.log("selectDefault: adding new default connection configurator", this.store.groups);
            const defaultConnection = getDefaultRealConnection(this.store.groups);
            if ( defaultConnection !== undefined ){
                this.config.connection = markRaw(toRaw(defaultConnection));
            }
        },
        },
    });

</script>
