<template>
    <div>
        <div id="statistics-container" style="width: 100%; border:5px solid #fff3cd; min-height: 200px;">
            <!-- min() keeps the 1024px floor from forcing horizontal overflow when the
                 viewport (minus the container border) is narrower than 1024px -->
            <div v-if="group !== undefined" style="width: 50%; min-width: min(1024px, 100%); margin-left: auto; margin-right: auto;">

                <h3>File info</h3>
                <div class="table-responsive">
                    <table class="table table-bordered table-sm" style="table-layout: fixed;">
                        <colgroup><col width="20%" align="right"></colgroup>
                        <thead class="table-dark">
                        <tr>
                            <th>Aspect</th>
                            <th>Value</th>
                        </tr>
                        </thead>
                        <tbody>
                            <tr v-if="group.filename !== ''">
                                <td>Filename</td>
                                <td>{{group.filename}}</td>
                            </tr>
                            <tr v-if="group.title !== ''">
                                <td>Title</td>
                                <td>{{group.title}}</td>
                            </tr>
                            <tr v-if="group.description !== ''">
                                <td>Description</td>
                                <td>{{group.description}}</td>
                            </tr>
                            <tr>
                                <td>qlog version</td>
                                <td>{{group.version}}</td>
                            </tr>
                            <tr v-if="Object.keys(group.summary).length > 0">
                                <td>Summary</td>
                                <td>{{JSON.stringify(group.summary, null, 4)}}</td>
                            </tr>
                            <tr>
                                <td>Trace count</td>
                                <td>{{visibleConnections.length}}</td>
                            </tr>
                            <tr>
                                <td>Total event count</td>
                                <td>{{totalEventCount}}</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                
                <StatisticsConnectionRenderer v-if="totalEventCount > 0" v-for="(connection,index) in visibleConnections" :key="'conn_' +index" :connection="connection" :index="index" />

            </div>
        </div>
    </div>
</template>

<style scoped>
    #toplevel > tr[role="row"] td:first-of-type {
        text-align: right;
        font-weight: bold;
        padding-right: 10px;
    }
</style>

<script lang="ts">
    import { defineComponent, type PropType } from "vue";
    import StatisticsConfig from "./data/StatisticsConfig";
    import * as qlog from '@/data/QlogSchema';
    import Connection from "@/data/Connection";

    import StatisticsConnectionRenderer from "@/components/stats/StatisticsConnectionRenderer.vue";

    export default defineComponent({
        name: "StatisticsRenderer",
        components: {
            StatisticsConnectionRenderer,
        },
        props: {
            config: {
                type: Object as PropType<StatisticsConfig>,
                required: true,
            },
        },
        computed: {
            group() {
                return this.config.group;
            },
            visibleConnections(): Array<Connection> {
                if ( !this.config.group ) {
                    return [];
                }

                return this.config.group.getConnections().filter( (c) => !c.wasAutoGenerated );
            },
            totalEventCount(): number {
                if ( !this.config.group ) {
                    return -1;
                }
                    
                let output = 0;

                for ( const trace of this.visibleConnections ){
                    output += trace.getEvents().length;
                }

                return output;
            },
            qlogns() {
                return qlog;
            },
        },
    });

</script>
