import QlogConnection from "@/data/Connection";
import QlogConnectionGroup from "@/data/ConnectionGroup";

// Helpers for the trace/connection selection UIs (ConnectionConfigurator + the
// per-tab configurators).
//
// "Real" connections are the ones that came from a loaded trace file.
// The sequence diagram renderer clones a lone trace to simulate the other
// vantage point ("Simulated, autogenerated trace : ..."), and that clone
// registers itself on the SAME ConnectionGroup (QlogConnection's constructor
// calls parent.addConnection(this)). Every other tab's dropdown would therefore
// start listing the simulated clone after the Sequence tab rendered once.
// These helpers give the configurators a shared, pure way to ignore those
// clones both when building option lists and when counting how many real
// choices the user actually has (the selection UI auto-hides at exactly one).
//
// NOTE: these are deliberately plain functions over plain arrays. The groups'
// connection arrays are markRaw'd, so computeds calling these only re-run when
// the reactive group list itself changes (file load/remove) — a sequence-tab
// visit appending a clone never resurfaces hidden pickers.

export function getRealConnections(group: QlogConnectionGroup): Array<QlogConnection> {
    return group.getConnections().filter( (connection) => !connection.wasAutoGenerated );
}

export function countRealConnections(groups: ReadonlyArray<QlogConnectionGroup>): number {
    let count = 0;
    for ( const group of groups ) {
        count += getRealConnections(group).length;
    }

    return count;
}

// groups that have at least one real (non-autogenerated) connection
export function getGroupsWithRealConnections(groups: ReadonlyArray<QlogConnectionGroup>): Array<QlogConnectionGroup> {
    return groups.filter( (group) => getRealConnections(group).length > 0 );
}

// the first non-autogenerated connection across all groups, in load order.
// Used by the configurators' selectDefault() so a default selection can never
// land on a simulated clone (regardless of where the clone sits in the array).
export function getDefaultRealConnection(groups: ReadonlyArray<QlogConnectionGroup>): QlogConnection | undefined {
    for ( const group of groups ) {
        for ( const connection of group.getConnections() ) {
            if ( !connection.wasAutoGenerated ) {
                return connection;
            }
        }
    }

    return undefined;
}
