<template>
    <div style="background-color: #e2d9f3; padding: 0px 10px;" >

        <div class="container-fluid">
            <!-- with exactly one real trace loaded there is nothing to choose: auto-select it
                 (selectDefault) and reclaim the space. Autogenerated sequence-diagram clones are
                 excluded from the count, so visiting the Sequence tab never resurfaces this UI. -->
            <div v-if="realConnectionCount > 1" class="row justify-content-center">
                <p style="margin-top: 10px;">Select a trace via the dropdown(s) below to browse its raw event stream</p>
            </div>
            <div v-if="realConnectionCount > 1" class="row justify-content-center">
                <ConnectionConfigurator v-if="config.connections.length > 0" :allGroups="store.groups" :connection="config.connections[0]" :canBeRemoved="false" :excludeAutoGenerated="true" :onConnectionSelected="onConnectionSelected" />
            </div>

            <div v-if="config.connections.length > 0" class="row justify-content-center">
                <div class="col-6">
                    <input v-model="filterInput" type="text" class="form-control" placeholder="Filter events (case-insensitive substring of type + summary)" aria-label="Filter events" />
                </div>
                <div class="col-3">
                    <select v-model="config.selectedCategory" class="form-select" aria-label="Filter by category">
                        <option value="">All categories</option>
                        <option v-for="category in categories" :key="category" :value="category">{{ category }}</option>
                    </select>
                </div>
            </div>

            <div v-if="store.outstandingRequestCount === 0 && store.groups.length === 0" class="alert alert-danger" role="alert">Please load a trace file to visualize it</div>
            <div v-else-if="store.groups.length === 0" class="alert alert-warning" role="alert">Loading files...</div>
        </div>

    </div>
</template>

<style scoped>
    .row {
        padding-bottom: 10px;
    }
</style>

<script setup lang="ts">
    import { computed, onBeforeUnmount, onMounted, onUpdated, ref, toRaw, watch } from "vue";
    import { markRaw } from "vue";

    import EventLogConfig from "./data/EventLogConfig";
    import { getEventLogIndex } from "./data/EventLogIndex";

    import ConnectionConfigurator from "@/components/shared/ConnectionConfigurator.vue";
    import { countRealConnections, getDefaultRealConnection } from "@/components/shared/helpers/ConnectionSelectionHelper";
    import { useConnectionStore } from "@/store/ConnectionStore";
    import Connection from "@/data/Connection";

    const props = defineProps<{
        config: EventLogConfig;
    }>();

    const store = useConnectionStore();

    // local, immediate input value; the shared config.filterText only updates after
    // the ~150 ms debounce below so filtering never runs per keystroke
    const filterInput = ref(props.config.filterText);
    let debounceTimer: ReturnType<typeof setTimeout> | undefined;

    watch(filterInput, (newValue) => {
        if (debounceTimer !== undefined) {
            clearTimeout(debounceTimer);
        }
        debounceTimer = setTimeout(() => {
            debounceTimer = undefined;
            props.config.filterText = newValue;
        }, 150);
    });

    onBeforeUnmount(() => {
        if (debounceTimer !== undefined) {
            clearTimeout(debounceTimer);
            debounceTimer = undefined;
        }
    });

    // category dropdown options come from the (WeakMap-cached, non-reactive) index;
    // toRaw keeps the WeakMap keyed on the raw connection object
    const categories = computed(() => {
        const connection = props.config.connections.length > 0 ? toRaw(props.config.connections[0]) : undefined;
        if (connection === undefined) {
            return [];
        }
        return getEventLogIndex(connection).categories;
    });

    // only re-runs when the reactive group list changes (the groups' connection arrays are
    // markRaw'd) — so the sequence renderer appending its simulated clone never flips this
    const realConnectionCount = computed(() => countRealConnections(store.groups));

    function onConnectionSelected(connection: Connection): void {
        console.log("EventLogConfigurator:onConnectionSelected : ", props.config, connection);

        props.config.connections = [ markRaw(toRaw(connection)) ];
        // the category list belongs to the previous connection; reset to "all"
        props.config.selectedCategory = "";
    }

    function selectDefault(): void {
        console.log("EventLogConfigurator:selectDefault : adding new default connection", store.groups);
        const defaultConnection = getDefaultRealConnection(store.groups);
        if (defaultConnection !== undefined) {
            props.config.connections = [ markRaw(toRaw(defaultConnection)) ];
        }
    }

    onMounted(() => {
        if (props.config.connections.length === 0 && store.groups.length > 0) {
            selectDefault();
        }
    });

    onUpdated(() => {
        if (props.config.connections.length === 0 && store.groups.length > 0) {
            selectDefault();
        }
    });
</script>
