import fs from "node:fs";
import path from "node:path";
import zlib from "node:zlib";
import { describe, expect, it } from "vitest";
import FileLoader from "../src/components/filemanager/data/FileLoader";
import {
    countRealConnections,
    getDefaultRealConnection,
    getGroupsWithRealConnections,
    getRealConnections,
} from "../src/components/shared/helpers/ConnectionSelectionHelper";
import QlogConnection from "../src/data/Connection";
import QlogConnectionGroup from "../src/data/ConnectionGroup";
import { QlogLoader } from "../src/data/QlogLoader";

const ROOT = path.resolve(process.cwd(), "../../..");
const QUICHE_CLIENT = path.join(ROOT, "Sample/Data/qlog/quiche/quiche-localhost-client.sqlog.gz");

function readMaybeGzip(filePath: string): Uint8Array {
    const bytes = fs.readFileSync(filePath);
    if (bytes.length >= 2 && bytes[0] === 0x1f && bytes[1] === 0x8b) {
        return zlib.gunzipSync(bytes);
    }
    return bytes;
}

function exactArrayBuffer(bytes: Uint8Array): ArrayBuffer {
    const copy = new Uint8Array(bytes.byteLength);
    copy.set(bytes);
    return copy.buffer;
}

// production path: FileLoader sniff/convert + QlogLoader, exactly like a file drop
async function loadGroup(filePath: string): Promise<QlogConnectionGroup> {
    const bytes = readMaybeGzip(filePath);
    const name = path.basename(filePath).replace(/\.(gz|gzip)$/i, "");
    const file = new File([exactArrayBuffer(bytes)], name, { type: "application/qlog" });
    const result = await FileLoader.Load(file, name);
    expect(result.error).toBeUndefined();

    const group: QlogConnectionGroup | undefined = QlogLoader.fromJSON(result.qlogJSON) ?? undefined;
    expect(group).toBeTruthy();
    expect(group!.getConnections().length).toBeGreaterThan(0);

    return group!;
}

// mirrors what SequenceDiagramD3Renderer.ensureMoreThanOneTrace does to a lone trace:
// clone() registers the copy on the SAME parent group via QlogConnection's constructor
function addSimulatedSibling(connection: QlogConnection): QlogConnection {
    const clone = connection.clone();
    clone.title = "Simulated, autogenerated trace : " + clone.title;
    clone.description = "Simulated, autogenerated trace : " + clone.description;
    clone.wasAutoGenerated = true;

    return clone;
}

describe("connection selection helpers (autogenerated-trace exclusion)", () => {
    it("excludes a sequence-diagram simulated sibling from a real corpus group", async () => {
        const group = await loadGroup(QUICHE_CLIENT);
        const original = group.getConnections()[0];

        expect(countRealConnections([group])).toBe(1);
        expect(getRealConnections(group)).toEqual([original]);
        expect(getDefaultRealConnection([group])).toBe(original);

        // the clone lands on the same group (this is exactly how it leaks into dropdowns)...
        addSimulatedSibling(original);
        expect(group.getConnections().length).toBe(2);

        // ...but every helper keeps ignoring it
        expect(countRealConnections([group])).toBe(1);
        expect(getRealConnections(group)).toEqual([original]);
        expect(getDefaultRealConnection([group])).toBe(original);
        expect(getGroupsWithRealConnections([group])).toEqual([group]);
    });

    it("counts real connections across multiple groups and finds them behind autogenerated ones", async () => {
        const clientGroup = await loadGroup(QUICHE_CLIENT);
        addSimulatedSibling(clientGroup.getConnections()[0]);

        // synthetic group where the autogenerated connection comes FIRST in array order
        const syntheticGroup = new QlogConnectionGroup();
        const generated = new QlogConnection(syntheticGroup);
        generated.title = "Simulated, autogenerated trace : synthetic";
        generated.wasAutoGenerated = true;
        const real = new QlogConnection(syntheticGroup);
        real.title = "real synthetic trace";

        expect(syntheticGroup.getConnections()[0]).toBe(generated); // ordering premise

        expect(countRealConnections([clientGroup, syntheticGroup])).toBe(2);
        // default selection must skip the leading autogenerated connection
        expect(getDefaultRealConnection([syntheticGroup])).toBe(real);
        expect(getDefaultRealConnection([clientGroup, syntheticGroup])).toBe(clientGroup.getConnections()[0]);
    });

    it("drops groups whose only connections are autogenerated", () => {
        const emptyGroup = new QlogConnectionGroup();
        const generatedOnlyGroup = new QlogConnectionGroup();
        const generated = new QlogConnection(generatedOnlyGroup);
        generated.wasAutoGenerated = true;

        expect(getRealConnections(generatedOnlyGroup)).toEqual([]);
        expect(countRealConnections([emptyGroup, generatedOnlyGroup])).toBe(0);
        expect(getGroupsWithRealConnections([emptyGroup, generatedOnlyGroup])).toEqual([]);
        expect(getDefaultRealConnection([emptyGroup, generatedOnlyGroup])).toBeUndefined();
    });
});
